[plugin]
id = "icanthink.alpha_solve_numerical"
name = "Alpha Solve Numerical"
version = "1.0.0"
python_libraries = ["numpy", "scipy", "sympy"]

[[functions]]
functionName = "solve_numerical"

[[functions]]
functionName = "evaluate_numerical"

# Proc macro that evaluates num() functions in LaTeX
[[proc_macros]]
functionName = "evaluate_num_functions"
metaFunctionName = "meta_evaluate_num_functions"

