[plugin]
id = "icanthink.alpha_solve_numerical"
name = "Alpha Solve Numerical"
version = "1.0.0"
python_libraries = ["numpy", "scipy", "sympy"]

[[functions]]
functionName = "solve_numerical"

[[functions]]
functionName = "evaluate_numerical"

